name: "Setup Go"
description: "Setup Go installs Go environment, lints and scans the project licenses."
inputs:
  go-version:
    description: "go version (default: version defined in root mod-file)"
    required: false
    default: "mod"
  linter-config-path:
    description: "golang-ci-lint config path"
    required: false
    default: "$GITHUB_ACTION_PATH/linter/.golangci.yml"
  linter-version:
    description: "golang-ci-lint version"
    required: false
    default: "v1.55.2"
  setup-script:
    description: "additional setup before linting"
    required: false
    default: "echo 'no additional setup needed'"
  skip-lint:
    description: "Skips linting when true"
    required: false
    default: "false"
  skip-scan:
    description: "Skips scanning when true"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      if: ${{ inputs.go-version == 'mod' }}
      with:
        go-version-file: './go.mod'
    - uses: actions/setup-go@v5
      if: ${{ inputs.go-version != 'mod' }}
      with:
        go-version: ${{ inputs.go-version }}
    - name: additional
      shell: bash
      run: eval ${{ inputs.setup-script }}
    - name: golangci-lint
      if: ${{ inputs.skip-lint == 'false' }}
      uses: golangci/golangci-lint-action@v4
      with:
        version: ${{ inputs.linter-version }}
        args: --config=${{ inputs.linter-config-path }} --timeout=5m
    - name: scan licenses
      shell: bash
      if: ${{ inputs.skip-scan == 'false' }}
      run: ${{ github.action_path }}/scanner/scan.sh
